CREATE TABLE sports (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(100) NOT NULL UNIQUE,
  icon VARCHAR(10) DEFAULT '🏆',
  governing_body VARCHAR(150),
  ranking_type VARCHAR(100),
  description TEXT,
  hero_image VARCHAR(255),
  sort_order INTEGER DEFAULT 0,
  is_active INTEGER DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE teams (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sport_id INTEGER NOT NULL,
  rank_position INTEGER NOT NULL,
  team_name VARCHAR(150) NOT NULL,
  team_type TEXT DEFAULT 'national',
  country_code CHAR(2),
  country_name VARCHAR(100),
  points DECIMAL(10,2) DEFAULT 0,
  points_label VARCHAR(50) DEFAULT 'pts',
  previous_rank INTEGER,
  trend TEXT DEFAULT 'same',
  logo_url VARCHAR(255),
  matches_played INTEGER DEFAULT 0,
  wins INTEGER DEFAULT 0,
  losses INTEGER DEFAULT 0,
  draws INTEGER DEFAULT 0,
  votes INTEGER DEFAULT 0,
  notable_achievement VARCHAR(255),
  is_active INTEGER DEFAULT 1,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (sport_id, rank_position, team_type)
);

CREATE TABLE site_settings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  setting_key VARCHAR(100) NOT NULL UNIQUE,
  setting_value TEXT,
  setting_group VARCHAR(50) DEFAULT 'general'
);

CREATE TABLE admin_users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  last_login DATETIME NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE activity_log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER,
  action TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO sports (id, name, slug, icon, governing_body, ranking_type, sort_order) VALUES
(1, 'Soccer / Football', 'soccer', '⚽', 'FIFA', 'FIFA Points', 1),
(2, 'Basketball', 'basketball', '🏀', 'FIBA', 'FIBA Points', 2),
(3, 'Cricket', 'cricket', '🏏', 'ICC', 'ICC Rating', 3),
(4, 'Tennis', 'tennis', '🎾', 'ATP/WTA', 'ATP/WTA Points', 4),
(5, 'American Football', 'american-football', '🏈', 'NFL/IFAF', 'Win-Loss Record', 5),
(6, 'Field Hockey', 'field-hockey', '🏑', 'FIH', 'FIH Points', 6),
(7, 'Volleyball', 'volleyball', '🏐', 'FIVB', 'FIVB Points', 7),
(8, 'Rugby Union', 'rugby', '🏉', 'World Rugby', 'World Rugby Points', 8),
(9, 'Baseball', 'baseball', '⚾', 'WBSC', 'WBSC Points', 9),
(10, 'Ice Hockey', 'ice-hockey', '🏒', 'IIHF', 'IIHF Points', 10);

INSERT INTO site_settings (setting_key, setting_value, setting_group) VALUES
('site_title', 'Sport Rank - World Sports Rankings', 'general'),
('site_tagline', "Official rankings for the world's top 10 sports", 'general'),
('meta_description', 'Discover up-to-date rankings for Soccer, Basketball, Cricket, Tennis, and more.', 'seo'),
('update_frequency', 'Weekly every Monday', 'general'),
('accent_color', '#F0A500', 'design'),
('footer_text', '© 2026 SportingRank. All rights reserved.', 'general'),
('google_analytics_id', '', 'analytics'),
('last_updated', '2026-05-01', 'general');

INSERT INTO admin_users (username, password_hash, email) VALUES
('admin', '$2y$10$NFyZJKAnwUOmmmQq0L8wEejkl1aZoSotFigPq2cBY67qLjtSO/kyS', 'admin@sportingrank.com');

INSERT INTO teams (sport_id, rank_position, team_name, country_code, points, team_type) VALUES
(1, 1, 'Argentina', 'ar', 1883.50, 'national'),
(1, 2, 'France', 'fr', 1853.11, 'national'),
(1, 3, 'Spain', 'es', 1844.33, 'national'),
(1, 4, 'England', 'gb', 1807.83, 'national'),
(1, 5, 'Brazil', 'br', 1784.37, 'national'),
(1, 6, 'Belgium', 'be', 1761.27, 'national'),
(1, 7, 'Portugal', 'pt', 1752.68, 'national'),
(1, 8, 'Netherlands', 'nl', 1748.24, 'national'),
(1, 9, 'Italy', 'it', 1729.40, 'national'),
(1, 10, 'Colombia', 'co', 1724.37, 'national'),
(1, 1, 'Real Madrid', 'es', 2500, 'club'),
(1, 2, 'Manchester City', 'gb', 2480, 'club'),
(1, 3, 'Liverpool', 'gb', 2420, 'club'),
(1, 4, 'Bayer Leverkusen', 'de', 2380, 'club'),
(1, 5, 'Inter Milan', 'it', 2350, 'club'),
(1, 6, 'Arsenal', 'gb', 2330, 'club'),
(1, 7, 'Bayern Munich', 'de', 2310, 'club'),
(1, 8, 'Barcelona', 'es', 2280, 'club'),
(1, 9, 'Paris Saint-Germain', 'fr', 2250, 'club'),
(1, 10, 'Borussia Dortmund', 'de', 2220, 'club'),
(2, 1, 'USA', 'us', 838.8, 'national'),
(2, 2, 'Serbia', 'rs', 758.2, 'national'),
(2, 3, 'Germany', 'de', 755.9, 'national'),
(2, 4, 'France', 'fr', 753.0, 'national'),
(2, 5, 'Canada', 'ca', 747.8, 'national'),
(2, 6, 'Spain', 'es', 746.7, 'national'),
(2, 7, 'Australia', 'au', 732.5, 'national'),
(2, 8, 'Argentina', 'ar', 731.1, 'national'),
(2, 9, 'Latvia', 'lv', 711.4, 'national'),
(2, 10, 'Lithuania', 'lt', 698.9, 'national'),
(2, 1, 'Boston Celtics', 'us', 100, 'club'),
(2, 2, 'Denver Nuggets', 'us', 98, 'club'),
(2, 3, 'Real Madrid', 'es', 95, 'club'),
(2, 4, 'Panathinaikos', 'gr', 94, 'club'),
(2, 5, 'Dallas Mavericks', 'us', 93, 'club'),
(2, 6, 'Minnesota Timberwolves', 'us', 92, 'club'),
(2, 7, 'Olympiacos', 'gr', 91, 'club'),
(2, 8, 'Fenerbahce', 'tr', 90, 'club'),
(2, 9, 'Monaco', 'fr', 89, 'club'),
(2, 10, 'Oklahoma City Thunder', 'us', 88, 'club'),
(3, 1, 'India', 'in', 122, 'national'),
(3, 2, 'Australia', 'au', 116, 'national'),
(3, 3, 'South Africa', 'za', 108, 'national'),
(3, 4, 'Pakistan', 'pk', 106, 'national'),
(3, 5, 'New Zealand', 'nz', 101, 'national'),
(3, 6, 'Sri Lanka', 'lk', 97, 'national'),
(3, 7, 'England', 'gb', 95, 'national'),
(3, 8, 'Bangladesh', 'bd', 86, 'national'),
(3, 9, 'Afghanistan', 'af', 82, 'national'),
(3, 10, 'West Indies', 'wi', 75, 'national'),
(3, 1, 'Kolkata Knight Riders', 'in', 95, 'club'),
(3, 2, 'Sunrisers Hyderabad', 'in', 92, 'club'),
(3, 3, 'Rajasthan Royals', 'in', 90, 'club'),
(3, 4, 'Royal Challengers Bengaluru', 'in', 88, 'club'),
(3, 5, 'Chennai Super Kings', 'in', 87, 'club'),
(3, 6, 'Perth Scorchers', 'au', 85, 'club'),
(3, 7, 'Sydney Sixers', 'au', 84, 'club'),
(3, 8, 'Surrey', 'gb', 82, 'club'),
(3, 9, 'Somerset', 'gb', 81, 'club'),
(3, 10, 'MI Cape Town', 'za', 80, 'club'),
(4, 1, 'Jannik Sinner', 'it', 11830, 'national'),
(4, 2, 'Carlos Alcaraz', 'es', 7120, 'national'),
(4, 3, 'Alexander Zverev', 'de', 6805, 'national'),
(4, 4, 'Novak Djokovic', 'rs', 6210, 'national'),
(4, 5, 'Daniil Medvedev', 'ru', 5230, 'national'),
(4, 6, 'Taylor Fritz', 'us', 4415, 'national'),
(4, 7, 'Andrey Rublev', 'ru', 4070, 'national'),
(4, 8, 'Casper Ruud', 'no', 3855, 'national'),
(4, 9, 'Grigor Dimitrov', 'bg', 3740, 'national'),
(4, 10, 'Alex de Minaur', 'au', 3545, 'national'),
(4, 1, 'Sinner Academy', 'it', 11830, 'club'),
(4, 2, 'Alcaraz Team', 'es', 7120, 'club'),
(4, 3, 'Zverev Base', 'de', 6805, 'club'),
(4, 4, 'Djokovic Center', 'rs', 6210, 'club'),
(4, 5, 'Medvedev Camp', 'ru', 5230, 'club'),
(4, 6, 'Fritz Pro', 'us', 4415, 'club'),
(4, 7, 'Rublev Elite', 'ru', 4070, 'club'),
(4, 8, 'Ruud Club', 'no', 3855, 'club'),
(4, 9, 'Dimitrov Squad', 'bg', 3740, 'club'),
(4, 10, 'De Minaur High', 'au', 3545, 'club'),
(5, 1, 'Kansas City Chiefs', 'us', 100, 'national'),
(5, 2, 'San Francisco 49ers', 'us', 98, 'national'),
(5, 3, 'Baltimore Ravens', 'us', 95, 'national'),
(5, 4, 'Detroit Lions', 'us', 92, 'national'),
(5, 5, 'Buffalo Bills', 'us', 89, 'national'),
(5, 6, 'Philadelphia Eagles', 'us', 87, 'national'),
(5, 7, 'Houston Texans', 'us', 85, 'national'),
(5, 8, 'Green Bay Packers', 'us', 83, 'national'),
(5, 9, 'Miami Dolphins', 'us', 80, 'national'),
(5, 10, 'Dallas Cowboys', 'us', 78, 'national'),
(5, 1, 'Kansas City Chiefs', 'us', 100, 'club'),
(5, 2, 'Baltimore Ravens', 'us', 98, 'club'),
(5, 3, 'Detroit Lions', 'us', 95, 'club'),
(5, 4, 'San Francisco 49ers', 'us', 94, 'club'),
(5, 5, 'Buffalo Bills', 'us', 93, 'club'),
(5, 6, 'Houston Texans', 'us', 92, 'club'),
(5, 7, 'Philadelphia Eagles', 'us', 91, 'club'),
(5, 8, 'Green Bay Packers', 'us', 90, 'club'),
(5, 9, 'Dallas Cowboys', 'us', 88, 'club'),
(5, 10, 'Cincinnati Bengals', 'us', 87, 'club'),
(6, 1, 'Netherlands', 'nl', 3168, 'national'),
(6, 2, 'Germany', 'de', 3035, 'national'),
(6, 3, 'Belgium', 'be', 2958, 'national'),
(6, 4, 'India', 'in', 2848, 'national'),
(6, 5, 'Australia', 'au', 2714, 'national'),
(6, 6, 'Argentina', 'ar', 2642, 'national'),
(6, 7, 'England', 'gb', 2627, 'national'),
(6, 8, 'Spain', 'es', 2445, 'national'),
(6, 9, 'Ireland', 'ie', 2090, 'national'),
(6, 10, 'France', 'fr', 2041, 'national'),
(6, 1, 'Kampong', 'nl', 100, 'club'),
(6, 2, 'Rot-Weiss Koln', 'de', 98, 'club'),
(6, 3, 'Bloemendaal', 'nl', 96, 'club'),
(6, 4, 'Gantoise', 'be', 94, 'club'),
(6, 5, 'Old Georgians', 'gb', 92, 'club'),
(6, 6, 'Club de Campo', 'es', 90, 'club'),
(6, 7, 'Mannheimer HC', 'de', 88, 'club'),
(6, 8, 'Waterloo Ducks', 'be', 86, 'club'),
(6, 9, 'Pinoke', 'nl', 84, 'club'),
(6, 10, 'Surbiton', 'gb', 82, 'club'),
(7, 1, 'Poland', 'pl', 408.95, 'national'),
(7, 2, 'France', 'fr', 358.24, 'national'),
(7, 3, 'Slovenia', 'si', 348.63, 'national'),
(7, 4, 'Japan', 'jp', 344.29, 'national'),
(7, 5, 'Italy', 'it', 344.21, 'national'),
(7, 6, 'USA', 'us', 343.78, 'national'),
(7, 7, 'Brazil', 'br', 315.44, 'national'),
(7, 8, 'Argentina', 'ar', 264.28, 'national'),
(7, 9, 'Canada', 'ca', 262.90, 'national'),
(7, 10, 'Germany', 'de', 262.02, 'national'),
(7, 1, 'Trentino Itas', 'it', 100, 'club'),
(7, 2, 'Jastrzebski Wegiel', 'pl', 98, 'club'),
(7, 3, 'Perugia', 'it', 96, 'club'),
(7, 4, 'Ziraat Bankasi', 'tr', 94, 'club'),
(7, 5, 'Lube Civitanova', 'it', 92, 'club'),
(7, 6, 'Halkbank', 'tr', 90, 'club'),
(7, 7, 'Zaksa Kedzierzyn-Kozle', 'pl', 88, 'club'),
(7, 8, 'Sada Cruzeiro', 'br', 86, 'club'),
(7, 9, 'Guaguas', 'es', 84, 'club'),
(7, 10, 'Berlin RV', 'de', 82, 'club'),
(8, 1, 'South Africa', 'za', 93.94, 'national'),
(8, 2, 'Ireland', 'ie', 90.33, 'national'),
(8, 3, 'New Zealand', 'nz', 89.41, 'national'),
(8, 4, 'France', 'fr', 87.97, 'national'),
(8, 5, 'England', 'gb', 87.24, 'national'),
(8, 6, 'Argentina', 'ar', 84.97, 'national'),
(8, 7, 'Scotland', 'gb', 82.90, 'national'),
(8, 8, 'Italy', 'it', 81.53, 'national'),
(8, 9, 'Fiji', 'fj', 81.14, 'national'),
(8, 10, 'Australia', 'au', 79.64, 'national'),
(8, 1, 'Toulouse', 'fr', 100, 'club'),
(8, 2, 'Leinster', 'ie', 98, 'club'),
(8, 3, 'Northampton Saints', 'gb', 95, 'club'),
(8, 4, 'Bulls', 'za', 93, 'club'),
(8, 5, 'La Rochelle', 'fr', 92, 'club'),
(8, 6, 'Munster', 'ie', 90, 'club'),
(8, 7, 'Saracens', 'gb', 88, 'club'),
(8, 8, 'Glasgow Warriors', 'gb', 87, 'club'),
(8, 9, 'Harlequins', 'gb', 85, 'club'),
(8, 10, 'Stormers', 'za', 84, 'club'),
(9, 1, 'Japan', 'jp', 4899, 'national'),
(9, 2, 'Mexico', 'mx', 4764, 'national'),
(9, 3, 'USA', 'us', 4492, 'national'),
(9, 4, 'South Korea', 'kr', 4350, 'national'),
(9, 5, 'Chinese Taipei', 'tw', 4170, 'national'),
(9, 6, 'Venezuela', 've', 3975, 'national'),
(9, 7, 'Netherlands', 'nl', 3288, 'national'),
(9, 8, 'Cuba', 'cu', 3121, 'national'),
(9, 9, 'Dominican Republic', 'do', 2667, 'national'),
(9, 10, 'Panama', 'pa', 2534, 'national'),
(9, 1, 'Los Angeles Dodgers', 'us', 100, 'club'),
(9, 2, 'Philadelphia Phillies', 'us', 97, 'club'),
(9, 3, 'New York Yankees', 'us', 95, 'club'),
(9, 4, 'Baltimore Orioles', 'us', 93, 'club'),
(9, 5, 'Cleveland Guardians', 'us', 91, 'club'),
(9, 6, 'Milwaukee Brewers', 'us', 89, 'club'),
(9, 7, 'Atlanta Braves', 'us', 87, 'club'),
(9, 8, 'Houston Astros', 'us', 85, 'club'),
(9, 9, 'Yomiuri Giants', 'jp', 83, 'club'),
(9, 10, 'Hanshin Tigers', 'jp', 81, 'club'),
(10, 1, 'Canada', 'ca', 4100, 'national'),
(10, 2, 'Czechia', 'cz', 4000, 'national'),
(10, 3, 'Switzerland', 'ch', 3900, 'national'),
(10, 4, 'Finland', 'fi', 3800, 'national'),
(10, 5, 'Sweden', 'se', 3700, 'national'),
(10, 6, 'USA', 'us', 3600, 'national'),
(10, 7, 'Germany', 'de', 3500, 'national'),
(10, 8, 'Slovakia', 'sk', 3400, 'national'),
(10, 9, 'Latvia', 'lv', 3300, 'national'),
(10, 10, 'Denmark', 'dk', 3200, 'national'),
(10, 1, 'Florida Panthers', 'us', 100, 'club'),
(10, 2, 'Edmonton Oilers', 'ca', 98, 'club'),
(10, 3, 'New York Rangers', 'us', 96, 'club'),
(10, 4, 'Dallas Stars', 'us', 94, 'club'),
(10, 5, 'Carolina Hurricanes', 'us', 92, 'club'),
(10, 6, 'Vancouver Canucks', 'ca', 90, 'club'),
(10, 7, 'Colorado Avalanche', 'us', 88, 'club'),
(10, 8, 'Boston Bruins', 'us', 86, 'club'),
(10, 9, 'ZSC Lions', 'ch', 84, 'club'),
(10, 10, 'Skelleftea AIK', 'se', 82, 'club');
